import * as T from 'three';
import {mouseDelta} from './mouse-look.mjs?v=lock1';
import {GLTFLoader} from './vendor/GLTFLoader.js';

// Adapted from the supplied APRL 610 Dalgu controller. Office collision data is RGB-D derived.
export async function installDalgu(viewer){
 const {scene,camera,controls,renderer,frames}=viewer;
 const [gltf,map,bytes]=await Promise.all([new GLTFLoader().loadAsync('./dalgu.glb'),fetch('./walkmap.json').then(r=>r.json()),fetch('./walkmap.bin').then(r=>r.arrayBuffer())]);
 const cells=new DataView(bytes),root=new T.Group(),model=gltf.scene;root.name='Dalgu';root.add(model);scene.add(root);
 let box=new T.Box3().setFromObject(model),size=box.getSize(new T.Vector3());const scale=Math.min(.82/size.y,.55/size.x,.75/size.z);model.scale.multiplyScalar(scale);box.setFromObject(model);const centre=box.getCenter(new T.Vector3());model.position.add(new T.Vector3(-centre.x,-box.min.y,-centre.z));box.setFromObject(model);size=box.getSize(new T.Vector3());const height=size.y,eye=height*.84,radius=.27;
 scene.add(new T.HemisphereLight(0xdceaff,0x62634e,2.1));const light=new T.DirectionalLight(0xffffff,2);light.position.set(2,6,3);scene.add(light);
 const panel=document.createElement('section');panel.id='dalguPanel';panel.innerHTML=`<div class="rule"></div><small>달구와 OFFICE 산책</small><div class="row"><button id="dalguEyes">달구 시점</button><button id="dalguFollow">따라가기</button></div><div id="walkActions" hidden><div class="row"><button id="dalguAuto">▶ 길 따라 산책</button><button id="dalguJump">점프 ×2</button></div><div class="row"><button id="dalguReset">안전한 길로</button><button id="dalguExit">둘러보기로</button></div><p>WASD / 방향키 이동 · Shift 달리기<br>마우스 고정으로 무제한 회전 · Space 2단 점프 · V 시점 전환<br>R 안전한 길로 · Esc 메뉴/커서 · 클릭 또는 L로 조종</p><div class="walk-pad"><button data-move="KeyW" aria-label="달구 앞으로">↑</button><button data-move="KeyA" aria-label="달구 왼쪽">←</button><button data-move="KeyS" aria-label="달구 뒤로">↓</button><button data-move="KeyD" aria-label="달구 오른쪽">→</button></div><label class="label" for="dalguEyeLevel">시야 높이 <span id="eyeLevelLabel">1.10 m</span></label><input id="dalguEyeLevel" aria-label="달구 시야 높이" type="range" min="0.55" max="1.4" step="0.05" value="1.1"><button id="dalguMouse" style="width:100%;margin-top:10px">마우스 시선: 켜짐</button><p id="walkState" role="status"></p></div><p>키 ${height.toFixed(2)}m · 폭 ${size.x.toFixed(2)}m<br>초록 길은 촬영자가 지나간 통로예요.</p>`;document.querySelector('#panel').insertBefore(panel,document.querySelector('#views'));
 const style=document.createElement('style');style.textContent='#panel{max-height:calc(100dvh - 48px);overflow:auto;scrollbar-width:thin}#dalguPanel small{letter-spacing:1px}#dalguPanel button{padding:9px 6px;font-size:12px}.walk-pad{display:flex;gap:7px}.walk-pad button{flex:1;touch-action:none}#walkState{min-height:18px;color:#8ce6c9}#walkMini{position:absolute;right:24px;top:78px;width:165px;height:235px;background:#101822e8;border:1px solid #ffffff30;border-radius:12px;pointer-events:none}body.dalgu-walk #help{display:none}@media(max-width:650px){#walkMini{right:10px;top:62px;width:100px;height:145px}#panel{max-height:calc(100dvh - 24px)}}';document.head.append(style);
 const mini=document.createElement('canvas');mini.id='walkMini';mini.width=198;mini.height=282;mini.hidden=true;mini.style.display='none';document.body.append(mini);const ctx=mini.getContext('2d');const backdrop=new Image();backdrop.src='./walkmap-preview.png';
 const $=id=>document.getElementById(id),keys=new Set(),pos=new T.Vector3(),look={last:null,paused:false};let dirtyUntil=0,eyeLevel=1.1,active=false,follow=true,yaw=0,pitch=0,vy=0,jumps=0,phase=0,drag=null,saved=null,auto=false,routeIndex=5,lastMini=0,blockedTime=0;
 function sample(x,z){const ix=Math.floor((x-map.origin[0])/map.resolution),iz=Math.floor((z-map.origin[1])/map.resolution);if(ix<0||iz<0||ix>=map.width||iz>=map.height)return{area:false,top:2.5,floor:-1.4};const k=(iz*map.width+ix)*4;return{area:!!cells.getUint8(k),top:cells.getUint8(k+1)/100,floor:cells.getInt16(k+2,true)/1000};}
 function blocked(x,z,feet=pos.y){for(let i=0;i<9;i++){const a=i*Math.PI/4,r=i===8?0:radius,s=sample(x+Math.cos(a)*r,z+Math.sin(a)*r);if(!s.area||s.floor+s.top>feet+.12&&s.top>.12)return true;}return false;}
 function nearestIndex(){let best=0,d=Infinity;map.route.forEach((q,i)=>{const dd=(q[0]-pos.x)**2+(q[1]-pos.z)**2;if(dd<d){d=dd;best=i;}});return best;}
 function spawn(index){dirtyUntil=performance.now()+1000;auto=false;updateAutoLabel();index=T.MathUtils.clamp(Math.round(index),0,frames.length-1);const p=frames[index].pose;pos.set(p[0][3],0,p[2][3]);pos.y=sample(pos.x,pos.z).floor+.025;yaw=Math.atan2(-p[0][2],-p[2][2]);pitch=0;vy=0;jumps=0;keys.clear();routeIndex=index;blockedTime=0;viewUpdate();return true;}
 function jump(){if(!active||jumps>=2)return false;vy=3.2;jumps++;auto=false;updateAutoLabel();return true;}
 function updateAutoLabel(){$('dalguAuto').textContent=auto?'Ⅱ 산책 정지':'▶ 길 따라 산책';}
 function drawMini(){ctx.clearRect(0,0,198,282);ctx.globalAlpha=.8;ctx.drawImage(backdrop,0,0,198,282);ctx.globalAlpha=1;const x=(pos.x-map.origin[0])/(map.width*map.resolution)*198,y=282-(pos.z-map.origin[1])/(map.height*map.resolution)*282;ctx.fillStyle='#fff0a4';ctx.beginPath();ctx.arc(x,y,4,0,7);ctx.fill();ctx.strokeStyle='#fff0a4';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-Math.sin(yaw)*12,y+Math.cos(yaw)*12);ctx.stroke();}
 function viewUpdate(){root.position.copy(pos);root.rotation.set(0,yaw+Math.PI,active&&keys.size?Math.sin(phase)*.025:0);root.visible=active&&follow;if(!active)return;camera.fov=75;camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);const target=pos.clone().add(new T.Vector3(0,eyeLevel,0));camera.position.copy(target);
  if(follow){const offset=new T.Vector3(0,.28-Math.sin(pitch)*.8,1.15*Math.cos(pitch)).applyAxisAngle(new T.Vector3(0,1,0),yaw),len=offset.length(),dir=offset.clone().normalize();let dist=.15;for(let d=.15;d<=len;d+=.04){const q=target.clone().addScaledVector(dir,d),s=sample(q.x,q.z);if(!s.area||q.y<s.floor+.12||s.top>.12&&s.floor+s.top>q.y-.12)break;dist=d;}camera.position.addScaledVector(dir,dist);camera.lookAt(pos.clone().add(new T.Vector3(-Math.sin(yaw)*.4,height*.95,-Math.cos(yaw)*.4)));}
  camera.updateProjectionMatrix();
 }
 function enter(third=false){dirtyUntil=performance.now()+1000;if(!active){viewer.stop();saved={pos:camera.position.clone(),q:camera.quaternion.clone(),target:controls.target.clone(),fov:camera.fov};spawn(viewer.currentIndex);active=true;}follow=third;controls.enabled=false;keys.clear();$('walkActions').hidden=false;mini.hidden=false;mini.style.display='block';document.body.classList.add('dalgu-walk');$('dalguEyes').classList.toggle('active',!follow);$('dalguFollow').classList.toggle('active',follow);viewUpdate();renderer.domElement.focus();setLookPaused(false);}
 function exit(){if(!active)return;active=false;look.paused=true;syncLook();auto=false;keys.clear();vy=0;jumps=0;drag=null;root.visible=false;if(document.pointerLockElement===renderer.domElement)document.exitPointerLock();controls.enabled=true;camera.position.copy(saved.pos);camera.quaternion.copy(saved.q);camera.fov=saved.fov;controls.target.copy(saved.target);camera.updateProjectionMatrix();controls.update();$('walkActions').hidden=true;mini.hidden=true;mini.style.display='none';document.body.classList.remove('dalgu-walk');$('dalguEyes').classList.remove('active');$('dalguFollow').classList.remove('active');updateAutoLabel();viewer.redraw();}
 $('dalguEyeLevel').oninput=e=>{eyeLevel=+e.target.value;dirtyUntil=performance.now()+1000;$('eyeLevelLabel').textContent=eyeLevel.toFixed(2)+' m';};
 // Pointer Lock uses relative motion: cursor position and screen edges never limit rotation.
 const lockHint=document.createElement('button');lockHint.id='dalguLockHint';lockHint.textContent='클릭해서 달구 조종 · Esc로 메뉴';lockHint.style.cssText='position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:3;background:#101822ee;padding:14px 20px';lockHint.hidden=true;document.body.append(lockHint);
 const aim=document.createElement('div');aim.id='dalguAim';aim.setAttribute('aria-hidden','true');aim.style.cssText='position:absolute;left:50%;top:50%;width:5px;height:5px;transform:translate(-50%,-50%);border:1px solid #fff9;border-radius:50%;pointer-events:none;z-index:2';aim.hidden=true;document.body.append(aim);
 let lockPending=false;
 function syncLook(){const locked=active&&document.pointerLockElement===renderer.domElement;look.paused=!locked;look.last=null;lockHint.hidden=!active||locked;aim.hidden=!locked;$('dalguMouse').textContent=locked?'마우스 고정: 켜짐 · Esc로 해제':'마우스 고정: 클릭해서 조종';}
 function lockFailed(error){console.warn('Pointer lock request failed',error?.name,error?.message);lockPending=false;syncLook();lockHint.textContent='뷰어 탭을 활성화한 뒤 화면을 직접 클릭해 주세요';}
 function requestLook(){if(!active||lockPending)return;if(document.pointerLockElement===renderer.domElement){syncLook();return;}look.last=null;lockHint.textContent='클릭해서 달구 조종 · Esc로 메뉴';renderer.domElement.focus();if(!document.hasFocus()){syncLook();lockHint.textContent='뷰어 탭을 활성화한 뒤 화면을 직접 클릭해 주세요';return;}if(!renderer.domElement.requestPointerLock){lockHint.textContent='이 브라우저는 마우스 고정을 지원하지 않아요';return;}if(navigator.userActivation&&!navigator.userActivation.isActive){syncLook();return;}lockPending=true;try{const result=renderer.domElement.requestPointerLock();result?.catch(lockFailed);}catch{lockFailed();}}
 function setLookPaused(value){if(value){keys.clear();auto=false;updateAutoLabel();if(document.pointerLockElement===renderer.domElement)document.exitPointerLock();look.paused=true;look.last=null;}else requestLook();syncLook();}
 document.addEventListener('pointerlockchange',()=>{lockPending=false;syncLook();keys.clear();if(look.paused){auto=false;updateAutoLabel();}dirtyUntil=performance.now()+500;viewer.redraw();});
 document.addEventListener('pointerlockerror',lockFailed);
 lockHint.onclick=requestLook;
 $('dalguMouse').onclick=()=>setLookPaused(document.pointerLockElement===renderer.domElement);
 $('dalguEyes').onclick=()=>enter(false);$('dalguFollow').onclick=()=>enter(true);$('dalguExit').onclick=exit;$('dalguJump').onclick=()=>{jump();renderer.domElement.focus();};$('dalguReset').onclick=()=>{auto=false;spawn(nearestIndex());updateAutoLabel();renderer.domElement.focus();};$('dalguAuto').onclick=()=>{auto=!auto;if(auto){routeIndex=nearestIndex();if(routeIndex>=map.route.length-2){spawn(0);auto=true;}}keys.clear();updateAutoLabel();renderer.domElement.focus();};
 const moving=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowLeft','ArrowDown','ArrowRight','ShiftLeft','ShiftRight'];
 window.addEventListener('keydown',e=>{if(!active||e.target.closest?.('input,select,textarea'))return;if(e.code==='Escape'){setLookPaused(true);keys.clear();return;}if(e.code==='KeyL'&&!e.repeat){setLookPaused(false);return;}if(e.code==='Space'){e.preventDefault();if(!e.repeat)jump();}else if(e.code==='KeyV'&&!e.repeat)enter(!follow);else if(e.code==='KeyR'&&!e.repeat){auto=false;spawn(nearestIndex());updateAutoLabel();}else if(moving.includes(e.code)){e.preventDefault();auto=false;updateAutoLabel();keys.add(e.code);}});window.addEventListener('keyup',e=>keys.delete(e.code));
 function clear(){keys.clear();drag=null;look.last=null;auto=false;updateAutoLabel();if(document.hidden||!document.hasFocus())setLookPaused(true);}window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);
 renderer.domElement.addEventListener('pointerdown',e=>{if(active&&e.button===0){renderer.domElement.focus();requestLook();}});
 renderer.domElement.addEventListener('pointerleave',()=>look.last=null);
 window.addEventListener('pointerup',()=>keys.clear());
 document.addEventListener('mousemove',e=>{if(!active)return;const delta=mouseDelta(look,{x:e.clientX,y:e.clientY,movementX:e.movementX,movementY:e.movementY,inside:e.target===renderer.domElement,locked:document.pointerLockElement===renderer.domElement});if(!delta)return;const [dx,dy]=delta;if(!dx&&!dy)return;dirtyUntil=performance.now()+250;yaw-=dx*.0025;pitch=T.MathUtils.clamp(pitch-dy*.0025,-1.1,1.1);auto=false;updateAutoLabel();});
 panel.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();auto=false;updateAutoLabel();keys.add(b.dataset.move);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.move);});
 function tick(dt){if(!active)return;if(auto||keys.size||jumps||drag)dirtyUntil=performance.now()+250;dt=Math.min(dt,.05);let dx=0,dz=0;if(auto){while(routeIndex<map.route.length-1&&Math.hypot(map.route[routeIndex][0]-pos.x,map.route[routeIndex][1]-pos.z)<.16)routeIndex++;const q=map.route[routeIndex],d=Math.hypot(q[0]-pos.x,q[1]-pos.z);if(d>.03){const step=Math.min(d,dt*.9);dx=(q[0]-pos.x)/d*step;dz=(q[1]-pos.z)/d*step;const target=Math.atan2(-dx,-dz);yaw+=Math.atan2(Math.sin(target-yaw),Math.cos(target-yaw))*Math.min(1,dt*5);pitch*=Math.exp(-dt*4);}else if(routeIndex===map.route.length-1){auto=false;updateAutoLabel();}}
  else{let x=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')),z=Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp'));const l=Math.hypot(x,z),speed=keys.has('ShiftLeft')||keys.has('ShiftRight')?1.9:1;if(l){dx=(x*Math.cos(yaw)+z*Math.sin(yaw))/l*speed*dt;dz=(-x*Math.sin(yaw)+z*Math.cos(yaw))/l*speed*dt;}}
  const before=pos.clone(),steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.025));for(let i=0;i<steps;i++){if(!blocked(pos.x+dx/steps,pos.z))pos.x+=dx/steps;if(!blocked(pos.x,pos.z+dz/steps))pos.z+=dz/steps;}phase+=Math.hypot(pos.x-before.x,pos.z-before.z)*11;
  const floor=sample(pos.x,pos.z).floor+.025;vy-=9.8*dt;const next=pos.y+vy*dt,s=sample(pos.x,pos.z);const support=s.top>.12?s.floor+s.top+.025:floor;if(vy<=0&&next<=support&&pos.y>=support-.12){pos.y=support;vy=0;jumps=0;}else pos.y=Math.max(floor,next);if(pos.y<=floor+.001){vy=0;jumps=0;}if(pos.y>floor+1.65-height){pos.y=floor+1.65-height;vy=Math.min(0,vy);}
  $('dalguJump').textContent=jumps?`점프 ${jumps}/2`:'점프 ×2';
  blockedTime=Math.hypot(dx,dz)>.001&&pos.distanceTo(before)<.002?blockedTime+dt:0;$('walkState').textContent=blockedTime>.7?'막히면 Space로 점프하거나 ‘안전한 길로’를 눌러 주세요.':auto?'촬영 경로를 따라 이동 중 · 이동키로 중지':follow?'따라가기 · V로 달구 시점':'달구 시점 · V로 따라가기';viewUpdate();if(performance.now()-lastMini>100&&backdrop.complete){drawMini();viewer.setWalkIndex(nearestIndex());lastMini=performance.now();}
 }
 spawn(5);root.visible=false;
 return{tick,enter,exit,jump,spawn,blocked,sample,avatar:root,get active(){return active;},get needsRender(){return active&&(auto||keys.size>0||jumps>0||drag||performance.now()<dirtyUntil);},get position(){return pos.clone();},get follow(){return follow;},get jumpCount(){return jumps;},get dimensions(){return{height,width:size.x,length:size.z,radius};},get auto(){return auto;}};
}
